### PR TITLE
Fix liveness.clearsale.com.br #1686

### PR DESCRIPTION
**Pull request by jellizaveta**
seems legit

### CODE REVIEW

**Comment by BlazDT** [comment]
Only seeing an empty page when opening the site.

**Comment by jellizaveta** [comment]
I noticed that `clearsale.com.br` redirected to `clear.sale`, which is a fraud protection service. This made me think that the domain might be unblocked.

**Review by BlazDT — APPROVED** [review]
As long their site is not broken by fraudsters who simply block URL domains to circumvent them.

**Comment by Alex-302** [comment]
> As long their site is not broken by fraudsters who simply block URL domains to circumvent them.

It does not work in this way.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
