### PR TITLE
www.anrdoezrs.net

### PR DESCRIPTION
**Pull request by jellizaveta**
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1130

### CODE REVIEW

**Review by zloyden — COMMENTED** [review]
Looks like we have already this rule.
```
! https://github.com/AdguardTeam/AdguardFilters/issues/28681
||anrdoezrs.net^
```

**Comment by Alex-302** [comment]
It cannot be resolved on my end even with Google or CF DNS

**Comment by Alex-302** [comment]
> I guess it is blocked by the rule below in the screenshot

Hmm. When I checked, it was blocked by third-party filters only.

**Comment by zloyden** [comment]
Strange, I don't have it on my side, only issue with our DNS.
Anyway, if you unblock the request, the destination page will open fine.

**Comment by jellizaveta** [comment]
I can reproduce this issue. I assume that it is not blocked because in the Swedish filter the domain is written as: www.anrdoezrs.net.

**Pull request merged**
