### PR TITLE
address https://github.com/easylist/easylist/pull/9904

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/easylist/easylist/pull/9904
As far as my search goes, these two servers are not used as 3p ads/tracker, no hit on publicwww.
@hirorpt Please also check if you have time.

### CODE REVIEW

**Comment by Alex-302** [comment]
Not sure what to do. I only see few your exclusions in filters.

**Comment by Yuki2718** [comment]
> Not sure what to do. I only see few your exclusions in filters.

This happens everywhere the VC domain is used as click-through. Only concern will be whether allowing this causes 3p ads/tracker come through, which I haven't confirmed so far.

**Comment by Alex-302** [comment]
> everywhere the VC domain is used as click-through

Could you please provide sample? Is this case popular?

**Comment by Yuki2718** [comment]
> 
> Could you please provide sample? Is this case popular?

Maybe not a very good example as this is 3p ads but click ad banner on `https://my-best.com/10175`. I'll soon block this in JPF. There is also a known valiants of `trj.valuecommerce.com/vcushion.js` used e.g. by `http://ck.jp.ap.valuecommerce.com/servlet/referral?sid=3088959&pid=886039106` link on `www.nifty.com`.

**Comment by Yuki2718** [comment]
> 
> Is this case popular?

"Everywhere" was probably an exaggeration but not too rare.

**Comment by Alex-302** [comment]
What about excluding blocking rule from DNS filter, or remove from Japanese filter?

**Comment by Yuki2718** [comment]
> What about excluding URL blocking rule from DNS filter, or remove from Japanese filter?

Will cause false negative, better to allow only those domain - I'll check whether `trj.valuecommerce.com` is used only for click-through or not lator.

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
