### PR TITLE
cartoon network roku app

### PR DESCRIPTION
**Pull request by BlazDT**
https://github.com/AdguardTeam/AdGuardDNS/issues/37

https://forum.adguard.com/index.php?threads/cartoon-network-roku-app-broken-by-auditude-com-filter.33113/

### CODE REVIEW

**Comment by Alex-302** [comment]
@BlazDT is it still required?

**Comment by BlazDT** [comment]
I do not have roku myself, opened for the user.

**Comment by BlazDT** [comment]
Can we merge after solving conflicts @Alex-302 ?

**Comment by Alex-302** [comment]
@BlazDT as I see, this domain is already blocked in SDN filter
image

**Comment by BlazDT** [comment]
Pull request is to exclude it.

**Comment by Alex-302** [comment]
Got it

**Pull request merged**
