### PR TITLE
Fix Outlook for Android

### PR DESCRIPTION
**Pull request by Alex-302**
removed obsolete rules, fixed in mobile filter

### CODE REVIEW

**Comment by ameshkov** [comment]
Well on the other hand, can they be loaded from other filter sources? Easyprivacy for instance?

**Comment by Alex-302** [comment]
I don't see these domains in all third-party filters

**Comment by Alex-302** [comment]
Maybe we can leave these exclusions as is.

**Comment by ameshkov** [comment]
> Maybe we can leave these exclusions as is.

Let's keep them just in case.

**Pull request closed without merging**
