### PR TITLE
fix #463 in HostlistsRegistry: remove internal IPs

### PR DESCRIPTION
**Pull request by Sergey-Lyapin**
https://github.com/AdguardTeam/HostlistsRegistry/issues/463

### CODE REVIEW

**Comment by Alex-302** [comment]
It is related to https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1224 and should be handled by [HostlistCompiler](https://github.com/AdguardTeam/HostlistCompiler)

**Comment by Sergey-Lyapin** [comment]
@Alex-302
But can we exclude these rules  temporarily until that task is completed?

**Comment by Alex-302** [comment]
> Is the above case included?

What is it?) Just invalid IP?

**Comment by AdamWr** [comment]
If I'm not wrong, rule like this:
```adblock
||10.32.17.182espn.hb.tt.omtrdc.net^
```
will be also excluded by this regex, or not?

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1646#issuecomment-1988442989

`{0,1}` can be replaced with `?`

**Comment by Alex-302** [comment]
@piquark6046 replaced. In general ok?

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1646#issuecomment-1988460044
I think so.

**Comment by Alex-302** [comment]
@Sergey-Lyapin Please update PR according to https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1646#issuecomment-1988307749

**Comment by Sergey-Lyapin** [comment]
@Alex-302 updated

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
