### PR TITLE
fix #83329 riotgames.sng.link

### PR DESCRIPTION
**Pull request by Sergey-Lyapin**
https://github.com/AdguardTeam/AdguardFilters/issues/83329

### CODE REVIEW

**Comment by AdamWr** [comment]
Maybe I don't understand how it works or something, but do you have an idea why this rule is already in filters even if this pull request wasn't merged yet?

<details><summary>Screenshots</summary>

image

image

</details>

**Comment by Alex-302** [comment]
Better investigate what is it and is it really must be blocked.

**Comment by Alex-302** [comment]
Subdomains of singular.net can be found here https://subdomainfinder.c99.nl/index.php There are few ad-related.

**Comment by Alex-302** [comment]
Look at these commits:
https://github.com/AdguardTeam/AdguardFilters/commit/df06b67cacc5606cd3272bc9ab6ba88991f19d6d
https://github.com/AdguardTeam/AdguardFilters/commit/c3049d5bb3393ffa7a3e1931b0d50f2193ccaf38

**Comment by Sergey-Lyapin** [comment]
@AdamWr 
I told to Andrey about this problem, it seems he fixed it.

**Comment by AdamWr** [comment]
>I told to Andrey about this problem, it seems he fixed it.

Okay, thank you for your reply.

**Pull request closed without merging**
