### PR TITLE
fix https://github.com/AdguardTeam/AdguardFilters/issues/145369

### PR DESCRIPTION
**Pull request by Yuki2718**
### To avoid invalid pull requests, please check and confirm following terms

- [x] This is not an ad/bug report
- [x] My code follows [syntax](https://adguard-dns.io/kb/general/dns-filtering-syntax/) of this project
- [x] I have performed a self-review of my own changes
- [x] My changes do not break web sites, apps and files structure

### If the problem does not fall under any category that is listed here, please write a comment below in corresponding section

- [ ] Missed ads
- [x] Website or app doesn't work properly
- [ ] Missed analytics or tracker
- [ ] Filters maintenance

### Enter the issue address

https://github.com/AdguardTeam/AdguardFilters/issues/145369
https://github.com/AdguardTeam/AdguardFilters/issues/84106#issuecomment-850401427

### Terms

- [x] By submitting this issue, I agree that pull request does not contain private info and all conditions are met

### CODE REVIEW

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by Alex-302** [comment]
I'm not sure if it is worth removing the rule because of one problem in the absence of complaints.

**Comment by Yuki2718** [comment]
Well, two: https://github.com/AdguardTeam/AdguardFilters/issues/84106#issuecomment-850401427
Movie broken by the rule. Actually this may be more important - https://github.com/AdguardTeam/AdguardFilters/issues/145369 is not too serious TBH.

**Comment by Alex-302** [comment]
Ok

**Review by Alex-302 — APPROVED** [review]

**Pull request merged**
