### PR TITLE
battery drain fix

### PR DESCRIPTION
**Pull request by BlazDT**
Sometimes 5-6 requests to this domain when it is blocked.

! apps, e. g. com.reddit.frontpage|com.spotify.music|app.hallow.android|com.adobe.reader|tv.twitch.android.app

Screenshot for twitch app can be seen her (user disabled DNS protection to see requesting app): https://imgur.com/a/CNG6zR3

### CODE REVIEW

**Comment by Alex-302** [comment]
I can't reproduce battery drain with Reddit and Spotify apps (installed few months ago)

**Comment by BlazDT** [comment]
Lots of requests when domain is blocked (via DNS on device).

**Comment by Alex-302** [comment]
Lots of requests is not a problem. Same with TabTrader, GooglePlay and some other apps (at least 4 apps with the similar behavior). I measured it a long time ago, and recently and did not detect battery drain.
Compare sessions of AccuBattery with/without blocking of this domain.

**Comment by hagezi** [comment]
If possible, increase the blocking TTL ;)

**Comment by Alex-302** [comment]
> If possible, increase the blocking TTL

Can be configured in AdGuard app or private DNS settings.

**Pull request closed without merging**
