### PR TITLE
Fix #14 Fixing PayPal interstitial links

### PR DESCRIPTION
**Pull request by Alex-302**
https://github.com/AdguardTeam/AdGuardDNS/issues/14

### CODE REVIEW

**Comment by TPS** [comment]
Does/should this apply to regular AdGuard client users?

**Comment by ameshkov** [comment]
The blocking rules came from other AdGuard filter lists so they will still block these requests. But now they won't be blocked on the DNS level.

**Comment by TPS** [comment]
But should they be?  The associated issue says that blocking this may prevent use of PayPal, right?

**Comment by ameshkov** [comment]
> But should they be blocked at all anyplace? The associated issue says that blocking this may prevent use of PayPal, right?

When the blocking occurs inside a browser, AdGuard is able to distinguish sub-requests from the "main frame" requests.

**Pull request merged**
