### PR TITLE
Italian ad servers

### PR DESCRIPTION
**Pull request by Alex-302**
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/243

### CODE REVIEW

**Comment by ameshkov** [comment]
wouldn't it be better to add them to the base filter?

**Comment by BlazDT** [comment]
I agree, to Base adservers, own Italian section like WE have dir Chinese.

**Comment by Alex-302** [comment]
Duplicating of Easylist Italy. Do they really required in Base filter?

**Comment by ameshkov** [comment]
> Duplicating of Easylist Italy. Do they really required in Base filter?

Well, then we can simply include easylist as a rules source, can't we?

**Comment by Alex-302** [comment]
> Well, then we can simply include easylist as a rules source, can't we?

We can, but in this case some sites, where hosted specific banners, will be blocked completely. These sites absent in this PR.

**Comment by ameshkov** [comment]
We can use just this file:
https://hg.adblockplus.org/easylistitaly/raw-file/tip/easylistitaly/easylistitaly_adservers.txt

**Comment by ameshkov** [comment]
done
https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/1e336f87a1787a73e0756a7b0038b969e6c522b4

**Comment by Alex-302** [comment]
ok

**Pull request closed without merging**
