### PR TITLE
Fix #299 onelink-translations.com

### LINKED ISSUE #299: ja.delta.com
This CNAME issue reported to EasyList forum also affects AdGuard DNS.
https://forums.lanik.us/viewtopic.php?f=64&t=44570&sid=99e831253c6bd073d310b5fab4937df0

delta

`onelink-translations.com`
need to be whitelisted.

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/299

### CODE REVIEW

**Comment by Alex-302** [comment]
@Yuki2718 which rule blocks it? This domain is not resolved on my end
<details>

image
</details>

**Comment by Yuki2718** [comment]
> 
> 
> @Yuki2718 which rule blocks it? This domain is not resolved on my end
> 
> image

You mean `ja.delta.com`?
`onelink-translations.com` is from EasyPrivacy and if you use AG-DNS, it won't be resolved.

**Comment by Alex-302** [comment]
But I cannot open yovoads.com even with google dns

**Comment by Yuki2718** [comment]
Test with Cloudflare DNS, the name will be resolved tho directly visiting the domain returns server error.

**Comment by Alex-302** [comment]
got it

**Comment by Yuki2718** [comment]
> 
> 
> got it

Nice. It seems not a matter of DNS but resolved anyway on Firefox, IDK.

**Pull request merged**
