### PR TITLE
fix beget.com https://github.com/AdguardTeam/AdguardFilters/issues/59946

### PR DESCRIPTION
**Pull request by BlazDT**
https://github.com/AdguardTeam/AdguardFilters/issues/59946

### CODE REVIEW

**Comment by AdamWr** [comment]
It seems that this rule is from `AdGuard Tracking Protection filter`, so maybe we should remove it.

**Comment by BlazDT** [comment]
Depends in where it was found.

**Comment by AdamWr** [comment]
It seems that it was added in this commit - https://github.com/AdguardTeam/AdguardFilters/commit/3e8e88c1ae4f64f83836b999150434d0cf03eafc#diff-fe4a06084b6827515916b40b51d36d67R26
So I guess it would be better to ask @Alex-302 about that.

**Comment by Alex-302** [comment]
Removed. It is just VPS hosting.

**Pull request closed without merging**
